version: '3'

services:
   mysql:
     image: mysql-index-tutorial:latest
     volumes:
       - mysql-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: tpch
       MYSQL_DATABASE: tpch
       MYSQL_USER: tpch
       MYSQL_PASSWORD: tpch
volumes:
    mysql-data:
